------------------------------------------------------------------------
--                              statusline                            --
------------------------------------------------------------------------
-- local gl = require('galaxyline')
-- local gls = gl.section
-- local condition = require('galaxyline.condition')
-- local u = require('utils')

-- local colors = {
--     bg = '#32302f',
--     bg2 = '#008080',
--     bg3 = '#d79921',
--     white = '#fbf1c7',
--     yellow = '#d79921',
--     cyan = '#008080',
--     grey = '#928374',
--     green = '#98971a',
--     purple = '#b16286',
--     orange = '#d65d0e',
--     blue = '#458588',
--     red = '#cc241d'
-- }

-- local checkwidth = function()
--   local squeeze_width  = vim.fn.winwidth(0) / 2
--   if squeeze_width > 50000 then
--     return true
--   end
--   return false
-- end
-- -- Custom file icon for atypical file types
-- local my_icons = require('galaxyline.provider_fileinfo').define_file_icon() -- get file icon color
-- -- scnvim:
-- my_icons['supercollider'] = {colors.blue, "✹"}
-- my_icons['help.supercollider'] = {colors.orange, "✹"}
-- my_icons['scnvim'] = {colors.yellow, "✹"}
-- -- Arch linux
-- my_icons['PKGBUILD'] = {colors.red, "☡"}

-- gls.left[1] = {
--     ViMode = {
--         provider = function()
--             local alias = {
--                 n = '  ☉ ',
--                 i = '  ✎ ',
--                 c = '  ⌨ ',
--                 v = '  ✄ ',
--                 [''] = '  ✄ ',
--                 t = 'zsh  ▧ '
--             }

--             local mode_color = {
--                 n = colors.blue,
--                 i = colors.orange,
--                 c = colors.yellow,
--                 v = colors.cyan,
--                 [''] = colors.cyan,
--                 t = colors.purple
--             }
--             -- Text for mode
--             local current_mode = alias[vim.fn.mode()]
--             -- Get color for mode
--             local current_bg = mode_color[vim.fn.mode()]
--             local current_fg = colors.white
--             -- Set color
--             vim.cmd(string.format('hi GalaxyViMode guibg=%s guifg=%s', current_bg, current_fg))
--             return current_mode
--         end,
--         separator = ' ',
--         separator_highlight = {colors.bg, colors.bg},
--         highlight = {colors.white, colors.green, 'bold'}
--     }
-- }

-- gls.left[2] = {
--     FileIcon = {
--         provider = 'FileIcon',
--         condition = condition.buffer_not_empty,
--         separator = ' ',
--         separator_highlight = {colors.bg, colors.bg},
--         highlight = {require('galaxyline.provider_fileinfo').get_file_icon_color, colors.bg}
--     }
-- }

-- gls.left[3] = {
--     FileName = {
--         provider = {'FileName'},
--         condition = condition.buffer_not_empty,
--         separator = ' ',
--         separator_highlight = {colors.bg, colors.bg},
--         -- separator_highlight = {colors.purple,colors.blue},
--         highlight = {colors.yellow, colors.bg}
--     }
-- }

-- gls.left[4] = {
--     GitIcon = {
--         provider = function() return ' ' end,
--         condition = condition.check_git_workspace,
--         highlight = {colors.orange, colors.bg}
--     }
-- }
-- gls.left[5] = {
--     GitBranch = {
--         provider = 'GitBranch',
--         separator = ' ',
--         separator_highlight = {colors.purple, colors.bg},
--         condition = condition.check_git_workspace,
--         highlight = {colors.yellow, colors.bg}
--     }
-- }

-- gls.left[6] = {
--     DiffAdd = {
--         provider = 'DiffAdd',
--         condition = condition.check_git_workspace,
--         separator = ' ',
--         separator_highlight = {colors.purple, colors.bg},
--         icon = '  ',
--         highlight = {colors.blue, colors.bg}
--     }
-- }
-- gls.left[7] = {
--     DiffModified = {
--         provider = 'DiffModified',
--         condition = condition.check_git_workspace,
--         separator = ' ',
--         icon = '  ',
--         highlight = {colors.blue, colors.bg}
--     }
-- }
-- gls.left[8] = {
--     DiffRemove = {
--         provider = 'DiffRemove',
--         condition = condition.check_git_workspace,
--         separator = ' ',
--         separator_highlight = {colors.purple, colors.bg},
--         icon = '  ',
--         highlight = {colors.red, colors.bg}
--     }
-- }

-- gls.mid[1] = {
--     Scnvim = {
--         provider = function()
--             local scstatus = Fn("scnvim#statusline#server_status", {})
--             return scstatus
--         end,
--         condition = function()
--             if Op("filetype") == "supercollider" then
--                 return true
--             else
--                 return false
--             end
--         end,
--         icon = ' 📡 ',
--         separator = '',
--         separator_highlight = {colors.blue, colors.bg},
--         highlight = {colors.blue, colors.bg}
--     }
-- }

-- gls.mid[2] = {
--     LspStatus = {
--         provider = function() return require('lsp-status').status() end,
--         separator = '',
--         separator_highlight = {colors.blue, colors.bg},
--         highlight = {colors.bg, colors.bg2}
--     }
-- }

-- gls.right[1] = {
--     Cwd = {
--         provider = function()
--             return vim.call("expand", "%")
--         end,
--         condition =checkwidth(),
--         -- condition = condition.hide_in_width,
--         icon = ' ⎙ ',
--         highlight = {colors.grey, colors.bg}
--     }
-- }

-- gls.right[2] = {
--     FileType = {
--         provider = function() return Op("filetype") end,
--         separator = ' ',
--         icon = ' ⌨ ',
--         separator_highlight = {colors.bg, colors.bg},
--         highlight = {colors.grey, colors.bg}
--     }
-- }

-- gls.right[3] = {
--     LineInfo = {
--         provider = 'LineColumn',
--         separator = ' ',
--         separator_highlight = {colors.bg, colors.bg},
--         highlight = {colors.grey, colors.bg}
--     }
-- }

-- gls.right[4] = {
--     PerCent = {
--         provider = 'LinePercent',
--         separator = ' ',
--         separator_highlight = {colors.bg, colors.bg},
--         highlight = {colors.yellow, colors.bg}
--     }
-- }

-- gls.right[5] = {
--     ScrollBar = {
--         provider = 'ScrollBar',
--         separator = ' ',
--         separator_highlight = {colors.bg, colors.bg},
--         highlight = {colors.yellow, colors.purple}
--     }
-- }

