[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0Rfile:///home/ranjith/Downloads/Contagion.2011.720p.1080p.All.BluRay.Version.HI.srt)
geometry="@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xce\0\0\0\x1c\0\0\at\0\0\x4,\0\0\x3\xcf\0\0\0\x1d\0\0\as\0\0\x4+\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xcf\0\0\0\x1d\0\0\as\0\0\x4+)"

[FullScreen]
pos=@Point(624 994)
screen=@Rect(0 0 1920 1080)
wide=false

[MainWindow]
ShowRemainingTime=true
adv-controls=0
bgSize=@Size(933 962)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/ranjith/Videos/Programming/My%20Developer%20Workflow%20-%20How%20I%20use%20i3%2C%20tmux%2C%20and%20vim.mp4, file:///home/ranjith/Videos/Programming/Introduction%20to%20FIFOs%20%28aka%20named%20pipes%29%20in%20C.mp4, "https://r3---sn-5hne6nsd.googlevideo.com/videoplayback?expire=1637942139&ei=G6-gYeSuDtKZ1gLf9LfwCg&ip=2a02%3Aa213%3A3240%3A9b80%3A2a7f%3Acfff%3Afef5%3Afa1e&id=o-AC8r3R-kSl9gLuTiB6I-XVyf5_ciDNQkpy9XOjKXyy_h&itag=18&source=youtube&requiressl=yes&mh=Qh&mm=31%2C26&mn=sn-5hne6nsd%2Csn-4g5lzney&ms=au%2Conr&mv=m&mvi=3&pl=33&initcwndbps=2020000&vprv=1&mime=video%2Fmp4&ns=_A8qjK0-109jTW5gcHLz34kG&gir=yes&clen=8858814&ratebypass=yes&dur=492.866&lmt=1448435869871602&mt=1637920149&fvip=3&fexp=24001373%2C24007246&c=WEB&n=7TtZwe5y6EwEGYWc&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPM7iRjtPTI3Uo3xsiCgsgeq3VstYBI5B7O5w8eDQOU1AiEAjJMuAtcuBfzvb8-jl1aOw2TwxodQ8v-GuXQXshzLkS8%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgSL908vlFznd-gV2_ojl2fEgVv5ZOke5V4hcWEQC_KqQCIFIJtEfwLkcjf4w5GcwRgZGmLAjfgkJU1wUb_V_CJtq9", "https://www.youtube.com/watch?v=5369xtKS42s", http://127.0.0.1:44400/0, http://127.0.0.1:24567/0, http://127.0.0.1:36474/0, http://127.0.0.1:12112/2, http://127.0.0.1:1964/0, http://127.0.0.1:58738/0, http://127.0.0.1:65109/0, file:///home/ranjith/Videos/Movies/The%20Big%20Lebowski/The%20Big%20Lebowski.mp4, file:///mnt/RanjithHD/Movies/Coen%20Brothers/The%20Big%20Lebowski/The%20Big%20Lebowski.mp4, file:///run/media/ranjith/TOSHIBA/ModernDanceShostakovsky.mp3, file:///home/ranjith/Downloads/Eastern%20Promises/Eastern%20Promises.mp4, file:///home/ranjith/Downloads/Contagion.mp4, file:///run/media/ranjith/Ranjith%20HD/Movies/Steven%20Soderbergh/The%20Girlfriend%20Experience.mp4, file:///home/ranjith/Downloads/The%20Informant.mp4
times=506416, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3767534, 2217648, 129235, 0, 0, 1511236, 0
