"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
linemode = "size"

[preview]
max_width = 1920
max_height = 1080

[plugin]
prepend_previewers = [{ name = "*.md", run = "glow" }]
prepend_fetchers = [
{ name = "*", id = "git", run = "git" },
]

[opener]
play = [
	{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
]

[open]
rules = [
	{ mime = "{audio,video}/*", use = [ "play", "reveal" ] },
]
