--enable-features=VaapiVideoDecoder,VaapiVideoEncoder,UseOzonePlatform,UseLibscret,CanvasOopRasterization,Vulkan,VulkanFromANGLE,DefaultANGLEVulkan,VaapiIgnoreDriverChecks,UseMultiPlaneFormatForHardwareVideo
--ozone-platform=wayland
--password-store=gnome-libsecret
--enable-gpu-rasterization
--enable-parallel-downloading
--enable-oop-rasterization
--enable-zero-copy
--use-gl=angle
--use-angle=vulkan
--enable-accelerated-video-decode
# --use-gl=desktop
# --enable-drdc
# --enable-oop-rasterization-ddl
# --disable-features=UseChromeOSDirectVideoDecoder,UseChromeOSDirectVideoEncoder
