--enable-gpu-rasterization
--enable-zero-copy
--enable-oop-rasterization
--enable-oop-rasterization-ddl
--enable-features=VaapiVideoDecoder,VaapiVideoEncoder,CanvasOopRasterization
--disable-features=UseChromeOSDirectVideoDecoder,UseChromeOSDirectVideoEncoder
--password-store=gnome
--enable-drdc
--enable-parallel-downloading
#--ozone-platform-hint=auto
