--enable-features=VaapiVideoEncoder,Vulkan,VulkanFromANGLE,DefaultANGLEVulkan,VaapiIgnoreDriverChecks,HdrAgtm,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoDecodeLinuxGL,TreesInViz
--password-store=kwallet6
--enable-experimental-web-platform-features
--enable-parallel-downloading
--use-gl=angle
--use-angle=vulkan
--force-color-profile=hdr10
--disable-quic
# --enable-gpu-rasterization
# --enable-oop-rasterization
# --enable-zero-copy
# --enable-accelerated-video-decode
# --enable-features=VaapiVideoDecoder,VaapiVideoEncoder,UseOzonePlatform,UseLibscret,CanvasOopRasterization,Vulkan,VulkanFromANGLE,DefaultANGLEVulkan,VaapiIgnoreDriverChecks,UseMultiPlaneFormatForHardwareVideo,HdrAgtm,WaylandLinuxDrmSyncobj
# --ozone-platform=wayland
# --ozone-platform-hint=wayland
