local tables = {}

------------------------------------------------------------------------
--                              FileTypes                             --
------------------------------------------------------------------------

---Filetypes with Language Servers
tables.lspfiles = {
    'bash',
    'sh',
    'zsh',
    'tex',
    'bib',
    'css',
    'cmake',
    'c',
    -- 'cs',
    'cpp',
    'glsl',
    'gd',
    'gdscript',
    'gdscript3',
    'objc',
    'opencl',
    'html',
    'javascript',
    'typescript',
    -- 'java',
    'json',
    'jsonc',
    'lua',
    'markdown',
    'org',
    'python',
    -- 'rust',
    'toml',
    'yaml',
}

tables.debugfiles = {
    'c',
    -- 'cs',
    'cpp',
    'gd',
    'gdscript',
    'gdscript3',
    'glsl',
    'objc',
    'opencl',
    'javascript',
    'typescript',
    'python',
}

tables.projectTypes = {
    'cpp',
    'electronics',
    'lua',
    'js',
    'python',
    'supercollider',
}

---Filetypes that are read-only
tables.ignoreFiles = {
    '',
    'qf',
    'fzf',
    'man',
    'oil',
    'lazy',
    'help',
    'noice',
    'netrw',
    'scnvim',
    'guihua',
    'Glance',
    'Outline',
    'trouble',
    'lspinfo',
    'orghelp',
    'NodeTree',
    'WhichKey',
    'gitcommit',
    'orgagenda',
    'gitrebase',
    'checkhealth',
    'dropbar_menu',
    'null-ls-info',
    'NeogitStatus',
    'OverseerList',
    'snacks_notif',
    'NeogitLogView',
    'DressingInput',
    'blink-cmp-menu',
    'NeogitDiffView',
    'TelescopePrompt',
    'NeogitCommitView',
    'snacks_dashboard',
    'TelescopeResults',
    'NeogitCommitSelectView',
    'blink-cmp-documentation',
}

tables.ignore_binaries_regex = {
    '*.png',
    '*.svg',
    '*.PNG',
    '*.jpg',
    '*.pdf',
    '*.gif',
    '*.jpeg',
    '*.svg',
    '*.odt',
    '*.doc*',
    '*.rtf',
    '*.wav',
    '*.blend',
}

------------------------------------------------------------------------
--                              Symbols                               --
------------------------------------------------------------------------

tables.nodeSymbols = {
    Argument = '🔧 ',
    Chapter = '📘 ',
    Element = '⚛ ',
    Key = '🔑 ',
    NormalCommand = '⚙ ',
    RuleSet = '📜 ',
    Section = '📜 ',
    Subsection = '📄 ',
    TableConstructor = '🛠️ ',
    TypeSpec = '🔖 ',
    UnquotedArgument = '❓ ',
    LinkageSpecification = '🔗 ',
}

---TreeSitter nodes selection
tables.tsNodes = {
    'argument',
    'array',
    'boolean',
    'break_statement',
    'call',
    'case_statement',
    'chapter',
    'class',
    'class',
    'constant',
    'constructor',
    'continue_statement',
    'declaration',
    'delete',
    'do_statement',
    'element',
    'enum',
    'enum_member',
    'event',
    'field',
    'for_statement',
    'function',
    'function_definition',
    'h1_marker',
    'h2_marker',
    'h3_marker',
    'h4_marker',
    'h5_marker',
    'h6_marker',
    'identifier',
    'if_statement',
    'interface',
    'key',
    'keyword',
    'linkage_specification',
    'macro',
    'method',
    'module',
    'namespace',
    'normal_command',
    'null',
    'number',
    'object',
    'operator',
    'package',
    'pair',
    'property',
    'reference',
    'repeat',
    'rule_set',
    'scope',
    'section',
    'specifier',
    'statement',
    'struct',
    'subsection',
    'switch_statement',
    'table_constructor',
    'type',
    'type_parameter',
    'type_spec',
    'unit',
    'unquoted_argument',
    'value',
    'variable',
    'while_statement',
}

------------------------------------------------------------------------
--                              Plugin lists                          --
------------------------------------------------------------------------

--- disable builtin vim plugins
tables.rtp = {
    'fzf',
    'tar',
    'zip',
    'gzip',
    'shada',
    'tutor',
    'tohtml',
    'matchit',
    'rplugin',
    'spellfile',
    'tarPlugin',
    'zipPlugin',
    'matchparen',
    'netrwPlugin',
}

--- TreeSitter parsers to keep installed
tables.ts_parsers = {
    'bash',
    'bibtex',
    'c',
    'cmake',
    'cpp',
    'comment',
    'css',
    'glsl',
    'gdscript',
    'godot_resource',
    'gdshader',
    'html',
    'java',
    'javascript',
    'json',
    'latex',
    'lua',
    'make',
    'markdown',
    'markdown_inline',
    'python',
    'query',
    'regex',
    'scheme',
    'supercollider',
    'toml',
    'vim',
    'vimdoc',
    'yaml',
}

tables.workspace_folderes = {
    '~/Documents/LaTeX',
    '~/Repositories/libraries/',
    '~/Repositories/Maintained/',
    '~/Workspaces/lua',
    '~/Workspaces/cpp',
    '~/Workspaces/electronics',
    '~/Workspaces/openFrameworks',
    '~/Workspaces/Unreal',
}

return tables
